### ISSUE TITLE
GoogleMap埋め込み

### ISSUE THREAD

**Issue by shogyomujo11** [roggram/hashimoto_ibento#3]
https://web-camp.io/magazine/archives/85020/
> HTMLページにGoogle mapを埋め込む方法

にある通りにやってみましょう。
貼り付ける先は index.html の、今imgがあるところです。
埋め込んだあとにwidthとheightの調整が必要になると思います。

**Comment by roggram** [comment]
記事のレスポンシブ対応に沿ったらwidth, height特に意識せずにいい感じになってくれた気がしています。
（触ったコードはpushしました。）

**Comment by shogyomujo11** [comment]
うまく導入できていると思います！
クローズします。
